### ISSUE TITLE
Дизайн

### ISSUE THREAD

**Issue by SigachevAV** [SigachevAV/ShadowFlex#4]
https://github.com/SigachevAV/ShadowFlex/blob/dev/Doca/Design.md

**Comment by Kkathenka** [comment]
![iPhone 14 Pro - 1 экран](https://github.com/SigachevAV/ShadowFlex/assets/99036555/c75637eb-6acc-4f75-bad3-e06ad9b277ec)
![iPhone 14 Pro - 1 экран(2)](https://github.com/SigachevAV/ShadowFlex/assets/99036555/9001b709-aafb-4ee9-b393-e6cb4658adf6)

**Comment by Kkathenka** [comment]
![iPhone 14 Pro - 1 экран(2)](https://github.com/SigachevAV/ShadowFlex/assets/99036555/78b2883f-3cc8-458c-bf44-64fdc1a78a9a)
![iPhone 14 Pro - 1 экран](https://github.com/SigachevAV/ShadowFlex/assets/99036555/b169914e-0380-4287-98fb-4e58e5c13d6a)
